const states = [{country: 'Maine', capital: 'Augusta'},
{country: 'New Hampshire', capital: 'Concord'},
{country: 'Vermont', capital: 'Montpelier'},
{country: 'Massachusetts', capital: 'Boston'},
{country: 'Rhode Island', capital: 'Providence'},
{country: 'Connecticut', capital: 'Hartford'},
{country: 'New York', capital: 'Albany'},
{country: 'Pennsylvania', capital: 'Harrisburg'},
{country: 'New Jersey', capital: 'Trenton'},
{country: 'Delaware', capital: 'Dover'},
{country: 'Maryland', capital: 'Annapolis'},
{country: 'West Virginia', capital: 'Charleston'},
{country: 'Ohio', capital: 'Columbus'},
{country: 'Michigan', capital: 'Lansing'},
{country: 'Indiana', capital: 'Indianapolis'},
{country: 'Illinois', capital: 'Springfield'},
{country: 'Wisconsin', capital: 'Madison'},
{country: 'Minnesota', capital: 'Saint Paul'},
{country: 'Iowa', capital: 'Des Moines'},
{country: 'Missouri', capital: 'Jefferson City'},
{country: 'North Dakota', capital: 'Bismarck'},
{country: 'South Dakota', capital: 'Pierre'},
{country: 'Nebraska', capital: 'Lincoln'},
{country: 'Kansas', capital: 'Topeka'},
{country: 'Kentucky', capital: 'Frankfort'},
{country: 'Virginia', capital: 'Richmond'},
{country: 'North Carolina', capital: 'Raleigh'},
{country: 'South Carolina', capital: 'Columbia'},
{country: 'Georgia', capital: 'Atlanta'},
{country: 'Florida', capital: 'Tallahassee'},
{country: 'Alabama', capital: 'Montgomery'},
{country: 'Mississippi', capital: 'Jackson'},
{country: 'Louisiana', capital: 'Baton Rouge'},
{country: 'Tennessee', capital: 'Nashville'},
{country: 'Arkansas', capital: 'Little Rock'},
{country: 'Oklahoma', capital: 'Oklahoma City'},
{country: 'Texas', capital: 'Austin'},
{country: 'Montana', capital: 'Helena'},
{country: 'Wyoming', capital: 'Cheyenne'},
{country: 'Colorado', capital: 'Denver'},
{country: 'New Mexico', capital: 'Santa Fe'},
{country: 'Idaho', capital: 'Boise'},
{country: 'Utah', capital: 'Salt Lake City'},
{country: 'Arizona', capital: 'Phoenix'},
{country: 'Nevada', capital: 'Carson City'},
{country: 'Washington', capital: 'Olympia'},
{country: 'Oregon', capital: 'Salem'},
{country: 'California', capital: 'Sacramento'},
{country: 'Alaska', capital: 'Juneau'},
{country: 'Hawaii', capital: 'Honolulu'},]

export function getUsaStates() {
    return states
}